[package]
name = "trails"
version = "0.1.0"
edition = "2021"
authors = ["The Cowboy AI, LLC <git@thecowboy.ai>"]
description = "A web-based AI model enhanced search platform"

[dependencies]
iced = { version = "0.13.1", features = ["canvas", "tokio", "debug"] }
